'yeah

class Artist {
    -name: String
    -active: boolean
    -instruments: ArrayList
    -id: int
    -debut: LocalDate
    -genres: ArrayList
    -discography: ArrayList
}

class Band {
    -name: String
}

class Solo {
    -stuff: a
}

class Musician {
    
}

Artist <|-- Band

Band -- Musician